/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, useGLTF } from '@react-three/drei';
import useTexturesModel from '../../../hooks/useTexturesModel';

function Monkey() {
  const { nodes, materials } = useGLTF(
    '/example/textture1/monkey uv unwarp.gltf',
  );
  const mat = useTexturesModel('/example/textture1', {
    height: '/example/textture1/height.jpg',
    metalic: '/example/textture1/metalic.jpg',
  });
  console.log(mat);
  return (
    <>
      <OrbitControls />
      <ambientLight intensity={3} />
      <directionalLight intensity={3} position={[0, 3, 0]} />

      <group dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Suzanne.geometry}
          material={nodes.Suzanne.material}
          position={[0, 0.361, 0]}
          scale={0.283}
        >
          <meshStandardMaterial {...mat} />
        </mesh>
      </group>
    </>
  );
}

export default Monkey;
