/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: brucassol (https://sketchfab.com/brucassol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chair-327203d10f524ed2aac78e59546821b3
Title: Chair
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { useRef } from 'react';

export default function Model(props: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/chair.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} scale={2.5} rotation-y="2">
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0.945]}
          scale={0.021}
        >
          <group
            name="7cb4ba39acb74acf8dd12c14f6121175fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Poltrona" position={[0, 0.14, 0]}>
                  <group name="Madeira_(2)">
                    <mesh
                      name="Madeira_(2)_Madeira_0"
                      castShadow
                      receiveShadow
                      geometry={nodes['Madeira_(2)_Madeira_0'].geometry}
                      material={materials.Madeira}
                    >
                      {/* <MeshReflectorMaterial mirror={0.2} /> */}
                    </mesh>
                  </group>
                  <group name="Almofada" position={[0, 1.5, -0.6]}>
                    <mesh
                      name="Almofada_Couro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Almofada_Couro_0.geometry}
                      material={materials.Couro}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/chair.glb');
