/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform
Files: scene.gltf [2.73MB] > scene-transformed.glb [43.69MB] (-1500%)
Author: heddathunell (https://sketchfab.com/heddathunell)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/butterfly-bb7a9781c2674e59a0f335fb8efb77d3
Title: Butterfly
*/

import { Clone, Float, useAnimations, useGLTF } from '@react-three/drei';
import { useControls } from 'leva';
import { useEffect, useRef } from 'react';

export function ButteryFlyModel(props: any) {
  const butterfly = useGLTF('/butterfly/butterfly.glb');
  const butterflyRef = useRef<any>();
  const { actions } = useAnimations(butterfly.animations, butterflyRef);
  const { position, scale, rotation } = useControls('butterfly', {
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 0.01,
  });
  useEffect(() => {
    console.log();
    actions.Object_0?.play();
  }, []);
  return (
    <>
      {/* <Float
        speed={1}
        rotationIntensity={2}
        floatIntensity={0.5}
        floatingRange={[0.8, 1]}
      >
        {/* top */}
      {/* <group visible={false}>
          <Clone ref={butterflyRef} object={butterfly.scene} scale={0.05} />
        </group> */}
      {/*
        <Clone object={butterfly.scene} scale={0.1} position={[20, -5, -8]} />
        <Clone
          object={butterfly.scene}
          scale={0.04}
          position={[0, -0.6, 0]}
          rotation={[0, 2.6, 0.05]}
        /> */}
      {/* </Float> */}
      {/* <group visible={false}>
        {/* middle */}
      <Float
        speed={1}
        rotationIntensity={2}
        floatIntensity={0.5}
        floatingRange={[0.8, 1]}
      >
        <Clone
          object={butterfly.scene}
          scale={0.07}
          position={[10, -5.6, -10]}
          rotation={[0, 2.6, 0.05]}
        />
        {/* <Clone
            object={butterfly.scene}
            scale={0.1}
            position={[20, -24, -8]}
          />
          <Clone
            object={butterfly.scene}
            scale={0.04}
            position={[0, -10, 0]}
            rotation={[0, 2.6, 0.05]}
          /> */}
      </Float>
      {/* </group>   */}
      {/* bottom */}
      {/* <Clone
        object={butterfly.scene}
        scale={0.05}
        rotation={[0.4, -1, 0]}
        position={[-4, -35, -10]}
      />

      <Clone object={butterfly.scene} scale={0.1} position={[24, -40, -8]} />

      <Clone
        object={butterfly.scene}
        scale={0.04}
        position={[0, -34, 0]}
        rotation={[0, 2.6, 0.05]}
      /> */}
    </>
  );
}

useGLTF.preload('/butterfly/butterfly.glb');
